### ISSUE TITLE
Update HoundCI settings

### ISSUE THREAD

**Issue by klaseskilson** [klaseskilson/vattentornet#129]
I suggest we add the following settings:

```yaml
# .hound.yml
fail_on_violations: true
coffeescript:
  config_file: coffeelint.json
```

```js
// coffeelint.json
// ...
  "max_line_length": {
    // changed from default 80 to be a bit more generous
    "value": 120,
    "level": "error",
    "limitComments": true
  },
// ...
```
